#!/usr/bin/env python3
"""
Fix DOT File Line Endings for Online Graphviz Viewers.

This script reads a `.dot` file generated by a tool like `torchviz` and
corrects its line endings from Windows-style (CRLF) to Unix-style (LF).

Some online Graphviz renderers (like http://viz-js.com/) are sensitive to line
endings and may fail to parse files with Windows CRLF endings. This script
ensures the file is compatible by converting it to the widely supported LF
format.

It also removes any null characters that might have been erroneously introduced.

Usage:
    # This script is configured with hardcoded input/output paths.
    python scripts/utils/model_export/fix_dot_file.py
"""

from pathlib import Path


def fix_dot_file(input_path: Path, output_path: Path):
    """
    Reads a DOT file, fixes its line endings to LF, and saves the result.

    Args:
        input_path (Path): The path to the source `.dot` file.
        output_path (Path): The path where the fixed file will be saved.
    """
    print(f"🔧 Fixing DOT file: {input_path}")

    if not input_path.exists():
        print(f"❌ ERROR: Input file not found at '{input_path}'")
        return

    try:
        with open(input_path, "r", encoding="utf-8") as f:
            content = f.read()

        # Replace Windows CRLF and classic Mac CR with Unix LF
        fixed_content = content.replace("\r\n", "\n").replace("\r", "\n")

        # Remove any null characters that can cause parsing issues
        fixed_content = fixed_content.replace("\x00", "")

        # Write the cleaned content with consistent LF line endings
        with open(output_path, "w", encoding="utf-8", newline="\n") as f:
            f.write(fixed_content)

        print(f"✅ Fixed DOT file saved: {output_path}")
        print("  - Ready for online Graphviz viewers like http://viz-js.com/")

    except Exception as e:
        print(f"❌ ERROR: An unexpected error occurred: {e}")


if __name__ == "__main__":
    # Define project root relative to this script's location
    project_root = Path(__file__).resolve().parents[3]

    # Configure input and output paths relative to the project root
    input_file = (
        project_root
        / "scripts"
        / "utils"
        / "model_export"
        / "WaveSourceMiniResNet_torchviz"
    )
    output_file = (
        project_root
        / "scripts"
        / "utils"
        / "model_export"
        / "WaveSourceMiniResNet_fixed.dot"
    )

    fix_dot_file(input_file, output_file)
