#!/usr/bin/env python3
"""
Test Script for the `SimpleActivationMaximizer`.

This script serves as a simple, targeted test to verify that the core
activation maximization logic is working correctly.

Workflow:
1.  Loads the best model from the main cross-validation experiment directory.
2.  Defines a hardcoded target layer (`wave_input_processor.0`) and filter index.
3.  Initializes the `SimpleActivationMaximizer`.
4.  Runs the optimization process to generate a pattern that maximizes the
    target filter's activation.
5.  Prints a summary and saves the comprehensive output plot generated by the
    maximizer.

This is not an interactive analysis tool but a functional test to ensure the
optimizer and plotting utilities are behaving as expected.

Usage:
    python scripts/activation_maximization/test_simple_activation_max.py
"""

import sys
from pathlib import Path

# Ensure project root is on sys.path so imports like 'src.*' resolve
sys.path.append(str(Path(__file__).parent.parent.parent))

import torch
import traceback
from src.activation_maximization.simple_activation_max import (
    SimpleActivationMaximizer,
    get_layer_by_path,
)
from src.activation_maximization.layer_hooks import find_best_cv_model
from src.models.wave_source_resnet import create_wave_source_model
from src.common.paths import get_experiments_dir


def test_simple_activation_maximization():
    """Test our custom single-channel activation maximization."""

    print("🚀 Simple Single-Channel Activation Maximization Test")
    print("=" * 60)

    # --- 1. Load Model ---
    print("🔍 Loading Best CV Model...")
    cv_results_path = get_experiments_dir() / "cv_full"
    model_info = find_best_cv_model(cv_results_path)
    if model_info is None:
        print(f"❌ No best model found in {cv_results_path}. Ensure CV results exist.")
        return

    fold_id, error, model_path = model_info
    print(f"✅ Found best model: Fold {fold_id} (error: {error:.4f}px)")
    print(f"   📄 Path: {model_path}")

    # Load model
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    model = create_wave_source_model(grid_size=128)

    checkpoint = torch.load(model_path, map_location=device)
    state_dict = checkpoint.get("model_state_dict", checkpoint)
    model.load_state_dict(state_dict)

    model = model.to(device).eval()
    print(f"✅ Model loaded: {sum(p.numel() for p in model.parameters()):,} parameters")

    # --- 2. Test Configuration ---
    layer_path = "wave_input_processor.0"  # Very first conv layer
    filter_idx = 5
    iterations = 1024
    learning_rate = 0.01

    print("\n🎯 Test Configuration:")
    print(f"   • Layer: {layer_path}")
    print(f"   • Filter: {filter_idx}")
    print(f"   • Iterations: {iterations}")
    print(f"   • Device: {device}")

    # --- 3. Run Optimization ---
    print("\n🚀 Running Simple Activation Maximization...")
    try:
        # Create an instance of the maximizer
        maximizer = SimpleActivationMaximizer(
            model, device=device, model_path=model_path
        )

        # Get the target layer and register the hook
        target_layer = get_layer_by_path(model, layer_path)
        layer_name = layer_path.replace(".", "_")
        maximizer.register_hook(layer_name, target_layer)

        # Define a structured save directory for this test's results
        save_dir = get_experiments_dir() / "activation_maximization" / "tests"
        save_dir.mkdir(parents=True, exist_ok=True)

        # Run the optimization
        results = maximizer.optimize_filter(
            layer_name=layer_name,
            filter_idx=filter_idx,
            iterations=iterations,
            learning_rate=learning_rate,
            use_real_data_init=True,
            tv_reg=0.05,
            l2_reg=0.01,
            save_dir=save_dir,
        )

        print("✅ Optimization completed successfully!")

        plot_path = results.get("plot_path")
        if plot_path:
            print(f"   Plot saved to: {plot_path}")
        else:
            print("   Plot path not found in results.")

        print("\n🎉 Test COMPLETED!")

    except Exception as e:
        print(f"❌ Optimization failed: {str(e)}")
        traceback.print_exc()

    finally:
        # Ensure hooks are always cleaned up
        if "maximizer" in locals() and maximizer is not None:
            maximizer.cleanup_hooks()


if __name__ == "__main__":
    test_simple_activation_maximization()
